module.exports = {
  NEWSLETTER_DATABASE_ID: process.env.NOTION_NEWSLETTER_DATABASE_ID,

  CHANNEL_DATABASE_ID: process.env.NOTION_CHANNEL_DATABASE_ID,

  NOTION_AUTH_KEY: process.env.NOTION_AUTH_KEY,
};
